# all access to actuator endpoints without security
management:
  security:
    enabled: false

# turn on actuator health check
endpoints:
  health:
    enabled: true

timeout: 100000

spring:
  profiles: offline
  
configuration:
  data:
    - name: 'testing every 20 seconds'
      cron: 0/20+*+*+*+*+?+* 
      endpoints:
        earmo: https://httpbin.org/get
        lchky: https://httpbin.org/ip
    - name: 'testing every 10 seconds with POST'
      cron: 0/10+*+*+*+*+?+*
      endpoints:
        post_endpoint: https://httpbin.org/post
      headers:
        CamelHttpMethod: POST
        UserID: Steve

---
spring:
  profiles: openshift
  
configuration:
  data:
    - name: "crddata every sunday at 9am"
      cron: 0+0+9+?+*+SUN+*
      endpoints:
        - http://hubx-api-communication:8080/api/SeasParser/GetCrdData
        - http://hubx-api-communication:8080/api/SeasParser/GetCrdData
    - name: 'tds every 15th minute'
      cron: 0+0,15,30,45+*+?+*+*+*
      endpoints:
        - http://hubx-api-communication:8080/api/TDSParser/UpdateBayInfo/6309/true/true/true
        - http://hubx-api-communication:8080/api/TDSParser/UpdateBayInfo/4029/true/true/true
    - name: 'seas every day at 9am'
      cron: 0+0+9+?+*+*+*
      endpoints:
        - http://hubx-api-communication:8080/api/SEASParser/GetPerformanceData/6309
        - http://hubx-api-communication:8080/api/SEASParser/GetPerformanceData/4029

---
spring:
  profiles: development

configuration:
  data:
    - name: "crddata every 15th second"
      cron: 0,15,30,45+*+*+*+*+?+*
      endpoints:
        earmo: http://hubx-api-communication:8080/api/SeasParser/GetCrdData
        lchky: http://hubx-api-communication:8080/api/SeasParser/GetCrdData
    - name: 'tds every 10th second'
      cron: 0,10,20,30,40,50+*+*+*+*+?+*
      endpoints:
        earmo: http://hubx-api-communication:8080/api/TDSParser/UpdateBayInfo/6309/true/true/true
        lchky: http://hubx-api-communication:8080/api/TDSParser/UpdateBayInfo/4029/true/true/true
    - name: 'seas every 0th, and 12th second'
      cron: 0,12,24,36,48,56+*+*+*+*+?+*
      endpoints:
        earmo: http://hubx-api-communication:8080/api/SEASParser/GetPerformanceData/6309
        lchky: http://hubx-api-communication:8080/api/SEASParser/GetPerformanceData/4029