# all access to actuator endpoints without security
management:
  security:
    enabled: false

# turn on actuator health check
endpoints:
  health:
    enabled: true

timeout: 100000

segment:
  list:
    - SEG1
    - SEG2

---
spring:
  profiles: openshift
crddata:
  period: 0+0+9+?+*+SUN+*
  earmo: http://hubx-api-communication:8080/api/SeasParser/GetCrdData
  lchky: http://hubx-api-communication:8080/api/SeasParser/GetCrdData
tds:
  period: 0+0,15,30,45+*+?+*+*+*
  earmo: http://hubx-api-communication:8080/api/TDSParser/UpdateBayInfo/6309/true/true/true
  lchky: http://hubx-api-communication:8080/api/TDSParser/UpdateBayInfo/4029/true/true/true
seas:
  period: 0+0+9+?+*+*+*
  earmo: http://hubx-api-communication:8080/api/SEASParser/GetPerformanceData/6309
  lchky: http://hubx-api-communication:8080/api/SEASParser/GetPerformanceData/4029

---
spring:
  profiles: development
crddata:
  period: 0,15,30,45+*+*+*+*+?+*
  earmo: https://hubx-api-communication-hubx-build.paas-dev-njrar-01.ams1907.com/api/SeasParser/GetCrdData
  lchky: https://hubx-api-communication-hubx-build.paas-dev-njrar-01.ams1907.com/api/SeasParser/GetCrdData
tds:
  period: 0,10,20,30,40,50+*+*+*+*+?+*
  earmo: https://hubx-api-communication-hubx-build.paas-dev-njrar-01.ams1907.com/api/TDSParser/UpdateBayInfo/6309/true/true/true
  lchky: https://hubx-api-communication-hubx-build.paas-dev-njrar-01.ams1907.com/api/TDSParser/UpdateBayInfo/4029/true/true/true
seas:
  period: 0,12,24,36,48+*+*+*+*+?+*
  earmo: https://hubx-api-communication-hubx-build.paas-dev-njrar-01.ams1907.com/api/SEASParser/GetPerformanceData/6309
  lchky: https://hubx-api-communication-hubx-build.paas-dev-njrar-01.ams1907.com/api/SEASParser/GetPerformanceData/4029
